### ISSUE TITLE
Add to plugins.json ?

### ISSUE THREAD

**Issue by AliSoftware** [dbgrandi/cocoapods-play#3]
Interesting plugin concept!
Is it production-ready, or still WIP?

If already working, don't forget to add it to [`plugins.json`](https://github.com/CocoaPods/cocoapods-plugins/blob/master/plugins.json) :wink:

**Comment by dbgrandi** [comment]
At the moment this is definitey **not** production ready.

This is a pretty hacky WIP from earlier this summer that I put on hold until swift/framework support got into CP...which is getting close. The goal would be to do something like `pod try` but build a framework that is imported to a playground.

**Comment by dbgrandi** [comment]
...but I'll definitely add it to the registry once it's working. :)
